<a href="https://colab.research.google.com/github/divya-dhina/DataScience/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array((1,2,3,4,5))
print(a)

[1 2 3 4 5]


In [ ]:
b=np.zeros(10)
print(b)
c=np.ones(10)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#values in a range(start,stop,step)
d=np.arange(1,10,2)
print(d)

[1 3 5 7 9]


In [ ]:
#evenly space values linspace(start,stop,nof terms)
f=np.linspace(1,10,3)
print(f)

[ 1.   5.5 10. ]


In [ ]:
#identity matrix
e=np.eye(3,3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(e.shape)#dimensions
print(e.ndim)#no of dimensions
print(e.size)#no of elements
print(e.dtype)#datatype of element

(3, 3)
2
9
float64


In [ ]:
print(np.add(b,c))
print(np.subtract(b,c))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]


In [ ]:
print(np.multiply(a,d))
print(np.divide(a,d))

[ 1  6 15 28 45]
[1.         0.66666667 0.6        0.57142857 0.55555556]


In [ ]:
print(np.dot(f,e))

[ 1.   5.5 10. ]


In [ ]:
g=[[1,2],[3,4],[5,6]]
print(g)
i=np.reshape(g,(2,3))#reshape(arr,(row,col))
print(i)

[[1, 2], [3, 4], [5, 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
h=[[6,7,8],[8,9,7]]
print(np.concatenate((i,h)))#rows appended
print(np.concatenate((i,h),axis=1))#columns appended

[[1 2 3]
 [4 5 6]
 [6 7 8]
 [8 9 7]]
[[1 2 3 6 7 8]
 [4 5 6 8 9 7]]


In [ ]:
np.split(c,5)#split c into 5 parts along row

[array([1., 1.]),
 array([1., 1.]),
 array([1., 1.]),
 array([1., 1.]),
 array([1., 1.])]

In [ ]:
np.split(c,[2,3])#split c with index as :2,2:

[array([1., 1.]), array([1.]), array([1., 1., 1., 1., 1., 1., 1.])]

In [ ]:
j=np.reshape(c,(10,1))
np.split(j,2,axis=1)

ValueError: ignored

In [ ]:
k=[1,2,3,4]
np.transpose(k)
l=[[1,2],
   [3,4]]
print(l)
np.transpose(l)

[[1, 2], [3, 4]]


array([[1, 3],
       [2, 4]])

In [ ]:
m=[[1,2,3],[4,5,6],[7,8,9]]
print(m)
np.transpose(m)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.random.shuffle(m)
print(m)

[[1, 2, 3], [7, 8, 9], [4, 5, 6]]


In [ ]:
#mathematical functions
print(np.sum(k))
print(np.mean(k))
print(np.median(k))
print(np.std(k))
print(np.min(k))
print(np.max(k))

10
2.5
2.5
1.118033988749895
1
4


In [ ]:
n=np.random.rand(3,3)
print(n)
p=np.random.random((3,3))
print(p)

[[0.69515926 0.96159816 0.6468565 ]
 [0.18867068 0.56220221 0.45850199]
 [0.8845974  0.37364829 0.24330119]]
[[0.72687934 0.01038026 0.9248553 ]
 [0.5083203  0.1144672  0.31822476]
 [0.6651678  0.82733615 0.05638265]]


In [ ]:
np.sort(n)

array([[0.6468565 , 0.69515926, 0.96159816],
       [0.18867068, 0.45850199, 0.56220221],
       [0.24330119, 0.37364829, 0.8845974 ]])

In [ ]:
print(np.sin(2*np.pi))
print(np.sin(np.array([np.pi/2,np.pi/4,np.pi/6,np.pi/6])))

-2.4492935982947064e-16
[1.         0.70710678 0.5        0.5       ]


In [ ]:
print(np.deg2rad(np.array([90,180,270,360])))

[1.57079633 3.14159265 4.71238898 6.28318531]


In [ ]:
print(np.rad2deg(2*np.pi))

360.0


In [ ]:
print(np.cos(np.pi/2))
print(np.tan(np.pi/4))

6.123233995736766e-17
0.9999999999999999


In [ ]:
#inverse trig func
print(np.arcsin(1))
print(np.rad2deg(np.arcsin(1)))#in degree
print(np.arccos(1))
print(np.arctan(0.999))

1.5707963267948966
90.0
0.0
0.784897913314115


In [ ]:
w=[[1,0,0],[0,1,0],[0,0,1]]
np.linalg.inv(w)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.linalg.det(w)

1.0

In [ ]:
np.linalg.eig(w)#eigen values and eigen vectors

(array([1., 1., 1.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))